In [1]:
import  numpy as np

### One dimensional Array

In [5]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

### More than one dimensioanl

In [38]:
a= np.array([[1, 2], [3, 4],[8,9]])
b=np.array([[3,4], [5,6], [7,8]])

In [39]:
print(a+b)

[[ 4  6]
 [ 8 10]
 [15 17]]


### Minimum dimension

In [18]:
a = np.array([1,2,3,], ndmin=2)
print(a)

[[1 2 3]]


### dtype parameters

In [29]:
a = np.array([1, 2, 3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [48]:
import numpy as np

A = np.array([[56,0.0, 4.4,68.0],
             [1.2, 104.0,52.0, 8.0],
             [1.8,135.0, 99.0, 0.9]])

print(A.shape)

(3, 4)


In [50]:
B =np.reshape(A, (4, 3))
print(B)

[[ 56.    0.    4.4]
 [ 68.    1.2 104. ]
 [ 52.    8.    1.8]
 [135.   99.    0.9]]


In [43]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [53]:
percentage = 100* A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [58]:
import numpy as np
a = np.random.randn(5,1) ## vs rp.random.randn(5)
print(a)

[[ 0.41164638]
 [ 0.1702719 ]
 [ 0.75871883]
 [-0.56924422]
 [-1.26573627]]


In [64]:
print(a.shape)
assert(a.shape == (5,1)) ## cool

(5, 1)


In [60]:
b = a.T
print(b)
print(b.shape)

[[ 0.41164638  0.1702719   0.75871883 -0.56924422 -1.26573627]]
(1, 5)


In [61]:
c = np.dot(a, b)
print(c)

[[ 0.16945274  0.07009181  0.31232386 -0.23432732 -0.52103576]
 [ 0.07009181  0.02899252  0.12918849 -0.09692629 -0.21551931]
 [ 0.31232386  0.12918849  0.57565427 -0.43189631 -0.96033794]
 [-0.23432732 -0.09692629 -0.43189631  0.32403898  0.72051305]
 [-0.52103576 -0.21551931 -0.96033794  0.72051305  1.6020883 ]]


In [79]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)

In [82]:
c = np.dot(a , b)
print(c)
print(c.shape)

[[ 0.45178504 -0.56810901]
 [-0.6206768   0.85469469]
 [ 0.67522719 -2.92933167]
 [-0.5608641   2.55277817]]
(4, 2)


In [91]:
x = np.array([[0,1,2,4], [5,6,7,8]])
print(x.shape)

(2, 4)


In [92]:
np.squeeze(x).shape

(2, 4)

In [99]:
a= np.array([[1,2,3,4],[54,56,67,7],[3,4,5,66]])
print(a)
print(a.shape[0])

[[ 1  2  3  4]
 [54 56 67  7]
 [ 3  4  5 66]]
3


In [100]:
a.shape

(3, 4)

In [106]:
a.reshape(a.shape[1], -1)

array([[ 1,  2,  3],
       [ 4, 54, 56],
       [67,  7,  3],
       [ 4,  5, 66]])

In [111]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
z = np.array([3, 0, 0, 3, 3])
#print("L2 = " + str(L2(yhat,y)))

In [112]:
print(np.dot(yhat,y)    )


2.2


In [119]:
print( np.dot(y-yhat, y-yhat))

0.43


In [120]:
import numpy as np
import h5py
    
    
def load_dataset():
    train_dataset = h5py.File('datasets/train_catvnoncat.h5', "r")
    train_set_x_orig = np.array(train_dataset["train_set_x"][:]) # your train set features
    train_set_y_orig = np.array(train_dataset["train_set_y"][:]) # your train set labels

    test_dataset = h5py.File('datasets/test_catvnoncat.h5', "r")
    test_set_x_orig = np.array(test_dataset["test_set_x"][:]) # your test set features
    test_set_y_orig = np.array(test_dataset["test_set_y"][:]) # your test set labels

    classes = np.array(test_dataset["list_classes"][:]) # the list of classes
    
    train_set_y_orig = train_set_y_orig.reshape((1, train_set_y_orig.shape[0]))
    test_set_y_orig = test_set_y_orig.reshape((1, test_set_y_orig.shape[0]))
    
    return train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes



In [121]:
load_dataset()

OSError: Unable to open file (unable to open file: name = 'datasets/train_catvnoncat.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)